inherit: 
    - models/TransformerTensorPCA.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 41

training:
    data: tensor
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 20000
    keep_every_steps: 100000
    train_steps: 500001
    task: tensor_pca
    data_kwargs: {}
    task_kwargs: {}
    check_full: False
    simplified: True
    lambda_: 10
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 21
            inc: 2
            interval: 100000
        sigma:
            start: 1
            end: 1
            inc: 0
            interval: 3000
out_dir: ../models/tensor_pca

wandb:
    name: "tensor_pca"
